// Package all holds the registration list of every built-in detector, from
// which the composition root builds its explicit catalog (ARCHITECTURE.md
// §6.2, decision D4). The list is GENERATED by go generate — never edited by
// hand — so adding a detector cannot create a merge-conflict hotspot, and no
// init() self-registration magic exists anywhere in the codebase. Duplicate
// detector IDs panic at catalog construction, failing CI rather than
// silently shadowing a detector.
//
// The go:generate mechanism and the generated all.go land in Phase 5; until
// then this package intentionally exports nothing.
package all
